// [Rules | ESLint Plugin Perfectionist](https://perfectionist.dev/rules)

export default {
	'perfectionistPlugin/sort-array-includes': [
		'error',
		{
			customGroups: [],
			groupKind: 'literals-first',
			groups: [],
			ignoreCase: true,
			order: 'asc',
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
			useConfigurationIf: {},
		},
	],
	'perfectionistPlugin/sort-exports': [
		'error',
		{
			groupKind: 'mixed',
			ignoreCase: true,
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionistPlugin/sort-heritage-clauses': [
		'error',
		{
			customGroups: {},
			groups: [],
			ignoreCase: true,
			order: 'asc',
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionistPlugin/sort-interfaces': [
		'error',
		{
			customGroups: [],
			groupKind: 'mixed',
			groups: [],
			ignoreCase: true,
			ignorePattern: [],
			newlinesBetween: 'ignore',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionistPlugin/sort-intersection-types': [
		'error',
		{
			groups: [],
			ignoreCase: true,
			newlinesBetween: 'ignore',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionistPlugin/sort-jsx-props': [
		'error',
		{
			customGroups: {},
			groups: [],
			ignoreCase: true,
			ignorePattern: [],
			order: 'asc',
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionistPlugin/sort-maps': [
		'error',
		{
			ignoreCase: true,
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionistPlugin/sort-named-exports': [
		'error',
		{
			groupKind: 'mixed',
			ignoreCase: true,
			order: 'asc',
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionistPlugin/sort-object-types': [
		'error',
		{
			customGroups: [],
			groups: [],
			ignoreCase: true,
			ignorePattern: [],
			newlinesBetween: 'ignore',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionistPlugin/sort-objects': [
		'error',
		{
			customGroups: {},
			destructuredObjects: true,
			groups: [],
			ignoreCase: true,
			ignorePattern: [],
			newlinesBetween: 'ignore',
			objectDeclarations: true,
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			styledComponents: true,
			type: 'natural',
			useConfigurationIf: {},
		},
	],
	'perfectionistPlugin/sort-sets': [
		'error',
		{
			customGroups: [],
			groupKind: 'literals-first',
			groups: [],
			ignoreCase: true,
			order: 'asc',
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
			useConfigurationIf: {},
		},
	],
	'perfectionistPlugin/sort-switch-case': [
		'error',
		{
			ignoreCase: true,
			order: 'asc',
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionistPlugin/sort-union-types': [
		'error',
		{
			groups: [],
			ignoreCase: true,
			newlinesBetween: 'ignore',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
};
