// Generated by Wrangler by running `wrangler types --x-include-runtime`
// run `cf:typegen` script to get types

interface Env {
	ASSETS: Fetcher;
	AUTH_KEY: string;
	SHIKI_MARKDOC_SERVICE: Fetcher;
}
